name: HTML Syntax Check (No Node)

on:
  push:
    branches: ["**"] # Trigger on push to any branch
  pull_request:
    branches: ["**"] # Trigger on PR to any branch

jobs:
  lint-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tidy
        run: sudo apt-get install tidy -y

      - name: Check HTML syntax using tidy
        run: |
          find . -name "*.html" -exec tidy -errors -q {} \; || exit 1
