name: HTML Syntax Check

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tidy
        run: sudo apt-get install tidy -y

      - name: Check HTML syntax using tidy
        run: |
          echo "Checking HTML files..."
          FAIL=0
          for file in $(find . -name "*.html"); do
            echo "Checking $file"
            tidy -qe "$file"
            if [ $? -ne 0 ]; then
              echo "HTML errors found in $file"
              FAIL=1
            fi
          done
          exit $FAIL
